print("1.feladat")

print("Hello world!")
print("2.feladat")
nev=input("Kérem a nevedet!")
print("Hello {}".format(nev))
print("3.feladat")
a=int(input("Kérek egy számot!"))
print("A szám kétszerese: {}".format(a*2))
print("4.feladat")
a=int(input("Kérek egy számot!"))
b=int(input("Kérek egy számot!"))
print("A két szám összege: {}".format(a+b))
print("A két szám különbsége {}".format(abs(a-b)))
print("A két szám szorzata: {}".format(a*b))
print("A két szám hányadosa {}".format(a/b))
print("5.feladat")
a=int(input("Kérem az él hosszát!"))
b=int(input("Kérem az él hosszát!"))
c=int(input("Kérem az él hosszát!"))
print("A téglatest térfogata: {}".format(a*b*c))
print("6.feladat")
print("A téglatest felszine {}".format(2*(a*b+a*c+b*c)))
print("7.feladat")
a=int(input("Kérem a befogo hosszát!"))
b=int(input("Kérem a befogo hosszát!"))
import math
print("Az átfogó hossza {}".format(math.sqrt(a*a+b*b)))
print("8.feladat")
a=int(input("Kérek egy számot!"))
b=int(input("Kérek egy számot!"))
print("A naggyobbik szám: {}".format(max(a,b)))
print("9.feladat")
a=int(input("Kérek egy számot!"))
b=int(input("Kérek egy számot!"))
c=int(input("Kérek egy számot!"))
print("A legkissebb szám: {}".format(min(a,b,c)))
print("10.feladat")
a=int(input("Kérek egy számot!"))
b=int(input("Kérek egy számot!"))
c=int(input("Kérek egy számot!"))
if a+b>c and a+c> b and b+c> a:
    print("Ez egy szerkeszthető háromszög!")
else:
    print("Ez nem egy szerkeszthető háromszög")
print("11.feladat")
a=int(input("Kérek egy számot!"))
b=int(input("Kérek egy számot!"))
print("A számtani közepük {}".format((a+b)/2))
print("A mértani közepük {}".format(math.sqrt(a*b)))
print("12.feladat")
a=int(input("Kérek a kör átmérőjét!"))
r=a/2
print("A kerülete {}".format(2*r*math.pi))
print("A területe {}".format(r*r*math.pi))

print("13.feladat")
a=int(input("Kérek egy számot!"))
i=0
print("{} -ig a pozitiv egész számok".format(a))
while i!= a:
    print(i+1, end=" ")
    #print("{}, ".format(i+1))
    i+=1
input()